INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('2305','The Adventures of Sherlock Holmes','Arthur Conan Doyle','Mystery/Detective, Fiction and Literature, Audiobook, Short Story Collection, Banned Books',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('31427','When Love Calls','Stanley J. Weyman','Romance',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('7150','20,000 Leagues Under the Sea','Jules Verne','Adventure, Nautical, Science Fiction, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('3986','Three Men in a Boat','Jerome K. Jerome','Satire, Humor, Fiction and Literature, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('26251','The Bible in its Making','Mildred Duff','Religion, History, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('6278','Hamlet','William Shakespeare','Drama, Poetry, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('31422','Legends of Gods and Ghosts (Hawaiian Mythology)','W.D. Westervelt','Myth',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('7088','The Art of War','Sun Tzu (Zi Sun)','Philosophy, History, War, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('2278','The Adventure of the Bruce-Partington Plans','Arthur Conan Doyle','Adventure, Mystery/Detective, Short Story',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('12488','By-Ways of Bombay','S. M. Edwardes','Non-fiction',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('9763','The Canterville Ghost','Oscar Wilde','Humor, Fiction and Literature, Ghost Stories, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('699','Pride and Prejudice','Jane Austen','Fiction and Literature, Harvard Classics, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('2310','A Study In Scarlet','Arthur Conan Doyle','Mystery/Detective, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('4215','The Arabian Nights','Andrew Lang','Fantasy, Banned Books, Fiction and Literature',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('4956','Paradise Lost','John Milton','Poetry, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('6694','Dracula','Bram Stoker','Horror, Gothic, Fiction and Literature, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('18312','Think and Grow Rich!','Napoleon Hill','Instructional, Business, Post-1930',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('2037','On the Origin of Species','Charles Darwin','Science, Audiobook, Non-fiction',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('2179','Hard Times','Charles Dickens','Fiction and Literature, Audiobook',10,100);
INSERT INTO books(isbn, title, author, genre, qty, price) VALUES('2604','The Beautiful and the Damned','F. Scott Fitzgerald','Fiction and Literature, Audiobook',10,100);
